style.css
margin-right: 10px;
adding this line in css
=> Sharanya1 lab patch 2

style.css
change the cursor style of add button to pointer
=> change cursor style on hover

style.css
I customized the scroll bar in order to align it with the design of the website.
I contributed it under hacktoberfest'22.
Screenshots:
If there is any other change, I need to incorporate, kindly notify :)
=> Customized the scroll bar

README.md
Fixed the indentation  for the read me
=> Updated The indentation

index.html, main.js, style.css
=> add darkmode

README.md
=> docs: add github stats

README.md
Enhance documentation
Fixes: https://github.com/Rick-mad-lab/Todolist/issues/4
- Added Local setup and contributing guidelines
- Added handling to listen to the user and prefill in input box for adding as todo
=> feat(readme): add details and enhance structure

main.js
I have HTML encoded the input to prevent from XSS which fixes the issue https://github.com/Rick-mad-lab/Todolist/issues/66
=> Update main.js to fix XSS 

CONTRIBUTING.md
I have added steps for forking and cloning with screenshots and links to tutorials for the same.
Please merge my pull request.
=> Improved contributing.md file

style.css
Mobile:
Desktop:
If approved, @Rick-mad-lab Please merge it. Thank you.
=> Improved UI for Todo Items

style.css
Reverts Rick-mad-lab/Todolist#72
=> Revert "Improved UI for Todo Items"

index.html, style.css
- Changed the Placement of Dark Mode Toggle.
- Replaced a Few Images With Fontawsome Icons (It will decrease the size of the project and increase the page speed).
- Added a Few Hover effects to make every button look more responsive on hover.
Happy Codding [❤️](https://emojipedia.org/red-heart/)
=> Changed the Placement of Dark Mode Toggle and CSS Fixes

package.json
I added package.json but it don't have any dependecies. If you have node_modules folder in your local repository do push it on remote, I will try to recover the dependencies then you can put it in .gitignore again
=> added package.json without any dependencies

style.css
Change Margin Position to mrgin-top="82px"  and Height ="Fit-Content"
=> Change Margin Position and Height

index.html, style.css
Adding card transparent effect to the  section of program
=> fix:  Refine Labels and Add Wrapper

index.html, style.css
Hey @Rick-mad-lab added the Navbar
This is how it looks rn  with Login button, This button needs to be changed to Logout when Logged in 
Do let me know if you want more changes.
=> Added Navbar  with necesaary design chnages

style.css
Aligned h2 in center for better view.
=> Aligned h2 in center for better view

style.css
Fixes Issue #64 
Also solved the problem generated by previous PR related to the same issue.
Screenshots:
Please merge if approved. Thank you.
=> Added Scrollbar.

main.js
I have fixed the bug.
#84 
@Rick-mad-lab
=> Fixed whitespace bug

index.html, style.css
issue #3 
Improved the layout of card and added CSS Effects to TODO
=> Enhanced the layout of card and added CSS Effects to TODO

index.html
@Rick-mad-lab issue #99 for adding footer resolved
=> footer was added to it

index.html, style.css
Changes the UI of the website added designs and transitions to the elements
=> Changed the UI and Added Animations and transitions

index.html, main.js, style.css
resolved issue #98 
Screenshots:
https://user-images.githubusercontent.com/95460021/197372042-8d60dc94-2f98-470a-981e-bb3c34feaaca.mp4
=> Customized the dark mode button

index.html, style.css
issue #106
https://user-images.githubusercontent.com/94471189/198519807-78a15390-a7da-4e5b-a213-167791c35cb9.mp4
=> Created footer

.github/ISSUE_TEMPLATE/bug.yml, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/docs.yml, .github/ISSUE_TEMPLATE/feature_request.yml, .github/ISSUE_TEMPLATE/other.yml
=> Created issue template

index.html, style.css
Hey  @Rick-mad-lab ,  The issue was in the footer the text was colliding with the social icons in the small screen view
Earlier it looked like:
Now :
=> Modified Footer

index.html, style.css
=> I've Added glass effect to the footer

index.html, style.css
@Rick-mad-lab I have made website as well as navbar responsive. please  merge my pr.
=> Make Website responsive
